package codigo;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);

        Utilidades.labelSetImgFast(escritor1, ImgNombres.ESCRITOR);
        Utilidades.labelSetImgFast(escritor2, ImgNombres.ESCRITOR);
        Utilidades.labelSetImgFast(escritor3, ImgNombres.ESCRITOR);

        Utilidades.labelSetImgFast(lector1, ImgNombres.LECTOR);
        Utilidades.labelSetImgFast(lector2, ImgNombres.LECTOR);
        Utilidades.labelSetImgFast(lector3, ImgNombres.LECTOR);
        Utilidades.labelSetImgFast(lector4, ImgNombres.LECTOR);
        Utilidades.labelSetImgFast(lector5, ImgNombres.LECTOR);

        Utilidades.labelSetImgFast(lector1Luz, ImgNombres.SEMAFORO_GRIS);
        Utilidades.labelSetImgFast(lector2Luz, ImgNombres.SEMAFORO_GRIS);
        Utilidades.labelSetImgFast(lector3Luz, ImgNombres.SEMAFORO_GRIS);
        Utilidades.labelSetImgFast(lector4Luz, ImgNombres.SEMAFORO_GRIS);
        Utilidades.labelSetImgFast(lector5Luz, ImgNombres.SEMAFORO_GRIS);

        Utilidades.labelSetImgFast(escritor1Luz, ImgNombres.SEMAFORO_GRIS);
        Utilidades.labelSetImgFast(escritor2Luz, ImgNombres.SEMAFORO_GRIS);
        Utilidades.labelSetImgFast(escritor3Luz, ImgNombres.SEMAFORO_GRIS);

        //Utilidades.labelSetTextoFast(escritor1Num, "");
        //Utilidades.labelSetTextoFast(escritor2Num, "");
        //Utilidades.labelSetTextoFast(escritor3Num, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtLibro = new javax.swing.JTextPane();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lector2 = new javax.swing.JLabel();
        lector3 = new javax.swing.JLabel();
        lector4 = new javax.swing.JLabel();
        lector1 = new javax.swing.JLabel();
        lector5 = new javax.swing.JLabel();
        lector1Luz = new javax.swing.JLabel();
        lector2Luz = new javax.swing.JLabel();
        lector3Luz = new javax.swing.JLabel();
        lector5Luz = new javax.swing.JLabel();
        lector4Luz = new javax.swing.JLabel();
        lector1Num = new javax.swing.JLabel();
        lector2Num = new javax.swing.JLabel();
        lector3Num = new javax.swing.JLabel();
        lector4Num = new javax.swing.JLabel();
        lector5Num = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        escritor1Luz = new javax.swing.JLabel();
        escritor1Num = new javax.swing.JLabel();
        escritor1 = new javax.swing.JLabel();
        escritor2Luz = new javax.swing.JLabel();
        escritor2Num = new javax.swing.JLabel();
        escritor2 = new javax.swing.JLabel();
        escritor3Luz = new javax.swing.JLabel();
        escritor3Num = new javax.swing.JLabel();
        escritor3 = new javax.swing.JLabel();
        libroTotalPalabras = new javax.swing.JLabel();
        finalTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escritores_Lectores");
        setResizable(false);

        txtLibro.setEditable(false);
        txtLibro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtLibro);

        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIniciar.setText("INICIAR SIMULACION");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("LECTORES:");

        lector2.setText("2");

        lector3.setText("3");

        lector4.setText("4");

        lector1.setText("1");

        lector5.setText("5");

        lector1Luz.setText("L");

        lector2Luz.setText("L");

        lector3Luz.setText("L");

        lector5Luz.setText("L");

        lector4Luz.setText("L");

        lector1Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lector1Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lector1Num.setText("0");

        lector2Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lector2Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lector2Num.setText("0");

        lector3Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lector3Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lector3Num.setText("0");

        lector4Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lector4Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lector4Num.setText("0");

        lector5Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lector5Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lector5Num.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ESCRITORES:");

        escritor1Luz.setText("L");

        escritor1Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        escritor1Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        escritor1.setText("1");

        escritor2Luz.setText("L");

        escritor2Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        escritor2Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        escritor2.setText("2");

        escritor3Luz.setText("L");

        escritor3Num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        escritor3Num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        escritor3.setText("3");

        libroTotalPalabras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        libroTotalPalabras.setText("Letras totales: 0");

        finalTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lector1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lector1Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lector1Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lector2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lector2Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lector2Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lector3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lector3Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lector3Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(escritor2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escritor2Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(escritor2Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lector4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lector4Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lector4Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lector5Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lector5Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lector5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escritor3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(escritor3Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(escritor3Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escritor1Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(escritor1Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(libroTotalPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalTxt)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libroTotalPalabras)
                    .addComponent(finalTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lector2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lector1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lector3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lector4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lector5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lector1Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector2Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector3Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector5Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector4Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector1Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector3Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector2Num, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lector4Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lector5Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escritor1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escritor1Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escritor1Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escritor2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escritor2Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escritor2Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escritor3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escritor3Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escritor3Num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        txtLibro.setText("");
        Utilidades.labelSetTextoFast(libroTotalPalabras, "Letras totales: 0");
        
        Utilidades.labelSetTextoFast(lector1Num, "0");
        Utilidades.labelSetTextoFast(lector2Num, "0");
        Utilidades.labelSetTextoFast(lector3Num, "0");
        Utilidades.labelSetTextoFast(lector4Num, "0");
        Utilidades.labelSetTextoFast(lector5Num, "0");
        
        Libro libro = new Libro(txtLibro, libroTotalPalabras);

        Escritor escritor1 = new Escritor(libro, escritor1Luz, escritor1Num);
        Escritor escritor2 = new Escritor(libro, escritor2Luz, escritor2Num);
        Escritor escritor3 = new Escritor(libro, escritor3Luz, escritor3Num);

        Lector lector1 = new Lector(libro, lector1Luz, lector1Num);
        Lector lector2 = new Lector(libro, lector2Luz, lector2Num);
        Lector lector3 = new Lector(libro, lector3Luz, lector3Num);
        Lector lector4 = new Lector(libro, lector4Luz, lector4Num);
        Lector lector5 = new Lector(libro, lector5Luz, lector5Num);

        escritor1.start();
        escritor2.start();
        escritor3.start();

        lector1.start();
        lector2.start();
        lector3.start();
        lector4.start();
        lector5.start();


    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //System.out.println("Current main thread: "+Thread.currentThread().getName());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel escritor1;
    private javax.swing.JLabel escritor1Luz;
    private javax.swing.JLabel escritor1Num;
    private javax.swing.JLabel escritor2;
    private javax.swing.JLabel escritor2Luz;
    private javax.swing.JLabel escritor2Num;
    private javax.swing.JLabel escritor3;
    private javax.swing.JLabel escritor3Luz;
    private javax.swing.JLabel escritor3Num;
    private javax.swing.JLabel finalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lector1;
    private javax.swing.JLabel lector1Luz;
    private javax.swing.JLabel lector1Num;
    private javax.swing.JLabel lector2;
    private javax.swing.JLabel lector2Luz;
    private javax.swing.JLabel lector2Num;
    private javax.swing.JLabel lector3;
    private javax.swing.JLabel lector3Luz;
    private javax.swing.JLabel lector3Num;
    private javax.swing.JLabel lector4;
    private javax.swing.JLabel lector4Luz;
    private javax.swing.JLabel lector4Num;
    private javax.swing.JLabel lector5;
    private javax.swing.JLabel lector5Luz;
    private javax.swing.JLabel lector5Num;
    private javax.swing.JLabel libroTotalPalabras;
    private javax.swing.JTextPane txtLibro;
    // End of variables declaration//GEN-END:variables

}
